version: '3'
services:
  redis-server: # specs of 1st container
    image: 'redis'
  node-app: # speccs of 2nd container
    restart: 'on-failure'
    build: .
    ports:
      - '8081:8081'  # dash is for an arrary